INSERT INTO EVENT VALUES(1, CURRENT_TIMESTAMP(), 'TestDescription1', CURRENT_TIMESTAMP(), 'testPlace1', 'MEETING');
INSERT INTO EVENT VALUES(2, CURRENT_TIMESTAMP(), 'TestDescription2', CURRENT_TIMESTAMP(), 'testPlace2', 'MEETING');
INSERT INTO EVENT VALUES(3, CURRENT_TIMESTAMP(), 'TestDescription3', CURRENT_TIMESTAMP(), 'testPlace3', 'MEETING');